### ISSUE TITLE
Onbetrouwbaarheid en traagheid REV

### ISSUE THREAD

**Issue by KevinvdBosch** [IDgis/adviesrobot-bevindingen#13]
Zoeken naar een oplossing voor de traagheid van het REV

**Comment by HermanAssink** [comment]
Bianca van Kooij meldt dat er nog gewerkt wordt aan de infrastructuur van het REV. Voorlopig geen alternatief zoeken tenzij later blijkt dat het onwerkbaar is.

**Comment by HermanAssink** [comment]
Vraagt teveel tijd voor deze 1e fase.
