### ISSUE TITLE
Keuze achtergrondkaart en andere algemene kaartlagen

### ISSUE THREAD

**Issue by KevinvdBosch** [IDgis/adviesrobot-bevindingen#22]
Voor nu staat de BRT als achtergrond ingesteld. Mogelijk moet dit later veranderd kunnen worden

**Comment by HermanAssink** [comment]
Naast BRT-Achtegrondkaart ook mogeljkheid bieden om in de viewer de PDOK luchtfoto te kiezen. In het advies (html&docx) wordt altijd BRT-A gebruikt.
Daarnaast is er de wens om de gemeentegrenzen te kunnen weergeven.
