### ISSUE TITLE
Foutmelding laptop Oostkracht10 bij openen link Adviesrobot

### ISSUE THREAD

**Issue by DaanODRA** [IDgis/adviesrobot-bevindingen#39]
![image](https://github.com/IDgis/adviesrobot-bevindingen/assets/164476969/bae40663-5783-4df5-a295-0976628dc103)
Deze foutmelding krijgen mensen die op een laptop van Oostkracht10 de tool willen openen

**Comment by KevinvdBosch** [comment]
Fout leek te komen door een interne technische blokkade
